/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns the current platform's texture sharing protocol name. */
export declare function getPlatform(): string
/**
 * napi-rs object returned from `receiveSharedTexture()`.
 *
 * Zero-copy GPU frame metadata, designed to be passed almost verbatim into
 * Electron's `sharedTexture.importSharedTexture({ textureInfo: ... })` in the
 * main process.
 *
 * `handle` is an 8-byte little-endian encoding of the platform-native shared
 * resource descriptor:
 * - Windows: an NT HANDLE (freshly minted for this frame via
 *   `IDXGIResource1::CreateSharedHandle`). Ownership transfers to the consumer;
 *   Electron will close it when the imported texture is released.
 * - macOS: an `IOSurfaceRef` pointer (retained by this call, released when the
 *   imported texture is released by Electron).
 *
 * The `ownerPid` field is the process ID in which the handle is valid, so
 * Chromium's GPU process can duplicate it correctly.
 */
export interface SharedTextureFrame {
  width: number
  height: number
  /**
   * Matches Electron's `SharedTextureImportTextureInfo.pixelFormat` values:
   * `"bgra" | "rgba" | "rgbaf16" | "nv12"`.
   */
  pixelFormat: string
  /**
   * Process ID that owns the handle. Almost always `process.pid` of the
   * Node process that called `receiveSharedTexture`.
   */
  ownerPid: number
  /** 8-byte little-endian encoding of the platform-native handle/pointer. */
  handle: Buffer
}
/** napi-rs object returned from receiveFrame() */
export interface ReceivedFrame {
  data: Buffer
  width: number
  height: number
}
/** napi-rs object returned from listSenders() */
export interface JsSenderInfo {
  name: string
  appName?: string
  uuid?: string
}
/** List all available texture senders (Syphon servers / Spout senders). */
export declare function listSenders(): Array<JsSenderInfo>
export declare class TextureSender {
  /**
   * Create a new texture sender.
   *
   * - `name`: Sender name visible in Spout/Syphon receivers
   * - `width`: Initial texture width
   * - `height`: Initial texture height
   */
  constructor(name: string, width: number, height: number)
  /**
   * Send a shared texture to Spout (Win) or Syphon (Mac).
   *
   * - `handle`: The native texture handle from Electron's paint event
   *   - Windows: `texture.textureInfo.handle` (DXGI HANDLE as number/BigInt)
   *   - macOS: `texture.textureInfo.handle` (IOSurfaceID as number)
   * - `width`: Texture width (from `textureInfo.codedSize.width`)
   * - `height`: Texture height (from `textureInfo.codedSize.height`)
   */
  send(handle: number, width: number, height: number): void
  /**
   * Send an IOSurface by direct pointer (macOS only).
   * Use this when you have an IOSurfaceRef buffer from Electron's shared texture.
   *
   * - `surface_buffer`: Buffer containing IOSurfaceRef pointer (8 bytes on 64-bit)
   * - `width`: Texture width
   * - `height`: Texture height
   */
  sendSurface(surfaceBuffer: Buffer, width: number, height: number): void
  /**
   * Stop the sender and release native resources immediately.
   * This is a terminal operation — the sender cannot be reused afterward.
   * Repeated calls are safe and idempotent.
   */
  stop(): void
  /**
   * Send raw RGBA buffer data to Syphon/Spout.
   * Use this for VideoFrame.copyTo() workflow where you have pixel data in a Buffer.
   *
   * - `data`: Buffer containing RGBA pixel data (BGRA format expected)
   * - `width`: Texture width in pixels
   * - `height`: Texture height in pixels
   * - `bytes_per_row`: Optional stride in bytes. Defaults to width * 4 if not provided.
   */
  sendRgbaBuffer(data: Buffer, width: number, height: number, bytesPerRow?: number | undefined | null): void
  /** Get the current platform name. */
  platform(): string
}
export declare class TextureReceiver {
  /**
   * Create a new texture receiver.
   *
   * - `sender_name`: Name of the Syphon server / Spout sender to connect to
   * - `app_name`: (macOS only) Filter by application name
   * - `server_uuid`: (macOS only) Connect by server UUID (highest priority)
   */
  constructor(senderName: string, appName?: string | undefined | null, serverUuid?: string | undefined | null)
  /**
   * Returns true if the server has output a new frame since the last receive.
   * Returns false if `stop()` has been called.
   */
  hasNewFrame(): boolean
  /**
   * Receive the current frame as RGBA pixel data.
   * Returns null if no frame is available or if `stop()` has been called.
   */
  receiveFrame(): ReceivedFrame | null
  /**
   * Receive the current frame as a GPU-shared texture descriptor.
   *
   * Returns `null` if no new frame is available or if `stop()` has been called.
   * The returned object can be handed to Electron's
   * `sharedTexture.importSharedTexture` after wrapping the `handle` Buffer
   * under the appropriate platform key (`ntHandle` on Windows,
   * `ioSurface` on macOS).
   *
   * Currently only Windows has a concrete implementation; macOS returns an
   * error until the Syphon IOSurface path is wired up.
   */
  receiveSharedTexture(): SharedTextureFrame | null
  /**
   * Returns true if the receiver has a valid connection to a server.
   * Returns false if `stop()` has been called.
   */
  isConnected(): boolean
  /**
   * Get the width of the last received texture.
   * Returns 0 if `stop()` has been called.
   */
  getWidth(): number
  /**
   * Get the height of the last received texture.
   * Returns 0 if `stop()` has been called.
   */
  getHeight(): number
  /**
   * Stop the receiver and release native resources immediately.
   * This is a terminal operation — the receiver cannot be reused afterward.
   * Repeated calls are safe and idempotent.
   */
  stop(): void
  /** Get the current platform name. */
  platform(): string
}
